CREATE
  TABLE COMMENTS
  (
    COMMENT_ID        VARCHAR2 (16) NOT NULL ,
    PARENT_COMMENT_ID VARCHAR2 (16) ,
    SUBMISSION_ID     VARCHAR2 (16) NOT NULL ,
    CONTENT CLOB NOT NULL ,
    VOTES    INTEGER NOT NULL ,
    ANALYZED CHAR (1) DEFAULT 'N' NOT NULL
  ) ;
ALTER TABLE COMMENTS ADD CONSTRAINT REDDITCOMMENT_PK PRIMARY KEY ( COMMENT_ID )
;


CREATE
  TABLE OCCURENCES
  (
    OCCURENCE   NUMBER (*,0) NOT NULL ,
    HEADID      NUMBER (*,0) NOT NULL ,
    TAILID      NUMBER (*,0) NOT NULL ,
    FREQUENCY   NUMBER (*,0) NOT NULL ,
    SUBREDDITID VARCHAR2 (16) NOT NULL
  ) ;
ALTER TABLE OCCURENCES ADD CONSTRAINT OCCURENCES_PK PRIMARY KEY ( OCCURENCE ) ;


CREATE
  TABLE SUBMISSIONS
  (
    SUBMISSION_ID VARCHAR2 (16) NOT NULL ,
    SUBREDDIT_ID  VARCHAR2 (16) NOT NULL ,
    VOTES         INTEGER NOT NULL ,
    TITLE         VARCHAR2 (1000) NOT NULL ,
    SELF_POST     CHAR (1) NOT NULL ,
    CONTENT CLOB NOT NULL
  ) ;
ALTER TABLE SUBMISSIONS ADD CONSTRAINT SUBREDDIT_PK PRIMARY KEY ( SUBMISSION_ID
) ;


CREATE
  TABLE SUBREDDITS
  (
    SUBREDDIT_ID     VARCHAR2 (16) NOT NULL ,
    NAME             VARCHAR2 (500) NOT NULL ,
    SUBSCRIBER_COUNT INTEGER NOT NULL
  ) ;
ALTER TABLE SUBREDDITS ADD CONSTRAINT SUBMISSIONS_PK PRIMARY KEY ( SUBREDDIT_ID
) ;


CREATE
  TABLE WORDHEAD
  (
    HEADID NUMBER (*,0) NOT NULL ,
    WORD1  VARCHAR2 (30 BYTE) NOT NULL ,
    WORD2  VARCHAR2 (30 BYTE) NOT NULL
  ) ;
ALTER TABLE WORDHEAD ADD CONSTRAINT WORDHEAD_PK PRIMARY KEY ( HEADID ) ;


CREATE
  TABLE WORDTAIL
  (
    TAILID NUMBER (*,0) NOT NULL ,
    WORD   VARCHAR2 (30 BYTE) NOT NULL
  ) ;
ALTER TABLE WORDTAIL ADD CONSTRAINT WORDTAIL_PK PRIMARY KEY ( TAILID ) ;


ALTER TABLE OCCURENCES ADD CONSTRAINT OCCURENCES_FK0 FOREIGN KEY ( HEADID )
REFERENCES WORDHEAD ( HEADID ) ;

ALTER TABLE OCCURENCES ADD CONSTRAINT OCCURENCES_FK1 FOREIGN KEY ( TAILID )
REFERENCES WORDTAIL ( TAILID ) ;

ALTER TABLE OCCURENCES ADD CONSTRAINT OCCURENCES_FK2 FOREIGN KEY ( SUBREDDITID
) REFERENCES SUBMISSIONS ( SUBMISSION_ID ) ;

ALTER TABLE COMMENTS ADD CONSTRAINT PARENT_COMMENT_ID FOREIGN KEY (
PARENT_COMMENT_ID ) REFERENCES COMMENTS ( COMMENT_ID ) ;

ALTER TABLE COMMENTS ADD CONSTRAINT REDDITCOMMENT_FK0 FOREIGN KEY (
SUBMISSION_ID ) REFERENCES SUBMISSIONS ( SUBMISSION_ID ) ;

ALTER TABLE SUBMISSIONS ADD CONSTRAINT SUBMISSIONS_ID FOREIGN KEY (
SUBREDDIT_ID ) REFERENCES SUBREDDITS ( SUBREDDIT_ID ) ;
